os: linux
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install -e .[dev]
script:
  - pytest
jobs:
  include:
    - stage: build docs
      python: 3.6
      script:
        - sphinx-build -n -b html -d docs/build/doctrees docs/source docs/build/html
        - touch docs/build/html/.nojekyll
      deploy:
        provider: pages
        cleanup: true
        token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: master
        local_dir: docs/build/html
