language: python
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5
install:
  - pip install -e .[dev]
script:
  - pytest
jobs:
  include:
    - stage: Build docs
      python: 3.7
      script: 
        - sphinx-build -n -b html -d docs/build/doctrees docs/source docs/build/html
        - touch docs/build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
